# Generated by Django 3.2.4 on 2021-06-27 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
